// [context: Rust, Android ARM64, compile-time + runtime string obfuscation]

use std::cell::RefCell;
use std::collections::HashMap;

thread_local! {
    static STRING_CACHE: RefCell<HashMap<u64, String>> = RefCell::new(HashMap::new());
}

/// XOR-decrypt a byte slice with a rolling key, return String.
pub fn decrypt_string(encrypted: &[u8], key: u8) -> String {
    let mut rolling = key;
    let bytes: Vec<u8> = encrypted.iter().map(|&b| {
        let plain = b ^ rolling;
        rolling = rolling.wrapping_add(b).wrapping_add(0x37);
        plain
    }).collect();
    String::from_utf8_lossy(&bytes).into_owned()
}

/// Encrypt a byte slice with a rolling key (for use in build scripts).
pub const fn xor_encrypt_const(input: &[u8], key: u8) -> ([u8; 256], usize) {
    let mut out = [0u8; 256];
    let mut rolling = key;
    let mut i = 0;
    while i < input.len() && i < 256 {
        let enc = input[i] ^ rolling;
        out[i] = enc;
        rolling = rolling.wrapping_add(enc).wrapping_add(0x37);
        i += 1;
    }
    (out, input.len())
}

/// Get an obfuscated string by ID. Decrypts on first access, caches thereafter.
pub fn get_string(id: u64, encrypted: &[u8], key: u8) -> String {
    STRING_CACHE.with(|cache| {
        let mut map = cache.borrow_mut();
        if let Some(s) = map.get(&id) {
            return s.clone();
        }
        let s = decrypt_string(encrypted, key);
        map.insert(id, s.clone());
        s
    })
}

/// Initialize all strings into the thread-local cache.
pub fn decrypt_all_strings() {
    // Trigger decryption of all known string IDs
    // This would be populated by the build-time obfuscation pass
    for (id, enc, key) in ENCRYPTED_STRINGS.iter() {
        STRING_CACHE.with(|cache| {
            let mut map = cache.borrow_mut();
            let s = decrypt_string(enc, *key);
            map.insert(*id, s);
        });
    }
}

/// Macro for inline obfuscated string literals.
#[macro_export]
macro_rules! obfstr {
    ($s:expr, $key:expr) => {{
        const INPUT: &[u8] = $s.as_bytes();
        const KEY: u8 = $key;
        // Encrypt at compile time (simplified: just XOR with key for first pass)
        // Full LLVM pass would do the rolling XOR at compile time
        static ENCRYPTED: &[u8] = {
            // Note: full const-eval of rolling XOR requires nightly + const_for
            // For stable, use a pre-encrypted byte literal generated by build.rs
            $s.as_bytes()  // fallback: no-op (replace with const-encrypted in production)
        };
        $crate::string_obf::decrypt_string(ENCRYPTED, KEY)
    }};
}

// Pre-encrypted string table populated by build.rs obfuscation pass
// Format: (id, encrypted_bytes, key)
static ENCRYPTED_STRINGS: &[(u64, &[u8], u8)] = &[
    // populated at build time by obfuscation pipeline
];
